version: "3.1"

services:
    db:
        image: postgres:14.2
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - "dbdata:/var/lib/postgresql/data"
            - "./_initdb:/docker-entrypoint-initdb.d"
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}"
            - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"
        ports:
            - 8001:80
        depends_on:
            - "db"
volumes:
    dbdata:
